  CREATE TABLE "VVA_DARC_CNTRL"."VVM_ADM_USERS" 
   (	"USER_ISID" VARCHAR2(30 CHAR), 
	"ROLE_NAME" VARCHAR2(30 CHAR), 
	"REGION_NAME" VARCHAR2(30 CHAR), 
	"COUNTRY_NAME" VARCHAR2(4000 CHAR), 
	"USER_STATUS" VARCHAR2(30 CHAR), 
	"CREATED_DATE" DATE, 
	"CREATED_BY_ID" VARCHAR2(30 CHAR), 
	"MODIFIED_DATE" DATE, 
	"MODIFIED_BY_ID" VARCHAR2(30 CHAR)
   )